perltidy files

diff --git a/smeserver-rocketchat/root/etc/e-smith/templates/etc/rc.d/init.d/rocketchat/30body b/smeserver-rocketchat/root/etc/e-smith/templates/etc/rc.d/init.d/rocketchat/30body
--- a/smeserver-rocketchat/root/etc/e-smith/templates/etc/rc.d/init.d/rocketchat/30body
+++ b/smeserver-rocketchat/root/etc/e-smith/templates/etc/rc.d/init.d/rocketchat/30body
@@ -1,15 +1,15 @@
 {
-use strict;
-use warnings;
-use esmith::ConfigDB;
+    use strict;
+    use warnings;
+    use esmith::ConfigDB;
 
-my $configDB = esmith::ConfigDB->open_ro or die("can't open Config DB");
+    my $configDB = esmith::ConfigDB->open_ro or die("can't open Config DB");
 
-my $rocketchatStatus = $configDB->get_prop( 'rocketchat', 'status' ) || 'disabled';
+    my $rocketchatStatus = $configDB->get_prop( 'rocketchat', 'status' ) || 'disabled';
 
-if ( $rocketchatStatus ne 'disabled' ) {
+    if ( $rocketchatStatus ne 'disabled' ) {
 
-    $OUT .=<<'EOF';
+        $OUT .= <<'EOF';
 
 
 # Check if any of $pid (could be plural) are running
@@ -42,146 +42,146 @@ killtree() {
 }
 
 checkpidexists() {
-	[ -d "/proc/$1" ] && return 0
-	return 1
+  [ -d "/proc/$1" ] && return 0
+  return 1
 }
 
 
 
 start() {
-	#this is to ensure forever is able to find out the correct root every time
-	export FOREVER_ROOT=/root/.forever
+  #this is to ensure forever is able to find out the correct root every time
+  export FOREVER_ROOT=/root/.forever
     
-	STATUS=$(/opt/rh/nodejs010/root/usr/lib/node_modules/forever/bin/forever --plain list | sed 's/data:\(\s*\[[0-9]*\]\s*\(rocketchat\)\s.*\)/\2-status:\1/;tx;d;:x')
-	
-	if ! [ -z "$STATUS" ]; then
-		echo "Service rocketchat already running"
-		return 0
-	fi
+  STATUS=$(/opt/rh/nodejs010/root/usr/lib/node_modules/forever/bin/forever --plain list | sed 's/data:\(\s*\[[0-9]*\]\s*\(rocketchat\)\s.*\)/\2-status:\1/;tx;d;:x')
+  
+  if ! [ -z "$STATUS" ]; then
+    echo "Service rocketchat already running"
+    return 0
+  fi
 
-	echo  "Starting rocketchat"
+  echo  "Starting rocketchat"
 
 
 
-	
-	# move to the directory from where the inital forever script was launched so that even if it is relative it works as expected
-	cd /opt/Rocket.Chat
+  
+  # move to the directory from where the inital forever script was launched so that even if it is relative it works as expected
+  cd /opt/Rocket.Chat
 
-	
+  
 
-	/opt/rh/nodejs010/root/usr/lib/node_modules/forever/bin/forever \
-	-a \
-	-l $LOGFILE \
-	--minUptime $MIN_UPTIME \
-	--spinSleepTime $SPIN_SLEEP_TIME \
-	--killSignal $KILL_SIGNAL \
-	 \
-	--uid rocketchat \
-	start main.js  2>&1 >/dev/null
-	
-	RETVAL=$?
+  /opt/rh/nodejs010/root/usr/lib/node_modules/forever/bin/forever \
+  -a \
+  -l $LOGFILE \
+  --minUptime $MIN_UPTIME \
+  --spinSleepTime $SPIN_SLEEP_TIME \
+  --killSignal $KILL_SIGNAL \
+   \
+  --uid rocketchat \
+  start main.js  2>&1 >/dev/null
+  
+  RETVAL=$?
 
- 	[ $RETVAL = 0 ] && touch $LOCKFILE
- 	return $RETVAL
+   [ $RETVAL = 0 ] && touch $LOCKFILE
+   return $RETVAL
 }	
 
 stop() {
-	#this is to ensure forever is able to find out the correct root every time
-	export FOREVER_ROOT=/root/.forever
+  #this is to ensure forever is able to find out the correct root every time
+  export FOREVER_ROOT=/root/.forever
 
-	echo -n "Shutting down rocketchat: "
+  echo -n "Shutting down rocketchat: "
 
     
-	STATUS=$(/opt/rh/nodejs010/root/usr/lib/node_modules/forever/bin/forever --plain list | sed 's/data:\(\s*\[[0-9]*\]\s*\(rocketchat\)\s.*\)/\2-status:\1/;tx;d;:x')
-	
-	if [ -z "$STATUS" ]; then
-		echo "Not running"
-		return 0
-	fi
+  STATUS=$(/opt/rh/nodejs010/root/usr/lib/node_modules/forever/bin/forever --plain list | sed 's/data:\(\s*\[[0-9]*\]\s*\(rocketchat\)\s.*\)/\2-status:\1/;tx;d;:x')
+  
+  if [ -z "$STATUS" ]; then
+    echo "Not running"
+    return 0
+  fi
 
-	# PID=$(<$PIDFILE) - Changed to detection based on actual PID from forever, sicne due to watchDirectory pid could dynamically change
+  # PID=$(<$PIDFILE) - Changed to detection based on actual PID from forever, sicne due to watchDirectory pid could dynamically change
     
-	PID=$(/opt/rh/nodejs010/root/usr/lib/node_modules/forever/bin/forever --plain list | sed -n -e '/data:\s*\[[0-9]*\]\s\(rocketchat\)\s/p' | awk '{print $7}')
-	
+  PID=$(/opt/rh/nodejs010/root/usr/lib/node_modules/forever/bin/forever --plain list | sed -n -e '/data:\s*\[[0-9]*\]\s\(rocketchat\)\s/p' | awk '{print $7}')
+  
 
-	if [ -z "$PID" ]; then
-		echo "Could not get pid"
-		return 0
-	fi
+  if [ -z "$PID" ]; then
+    echo "Could not get pid"
+    return 0
+  fi
 
-	#run in background, since recent changes in forever, now blocks stop call with SIGTERM is finished
-	#but we want to wait till some time and forcibly kill after elapsed time
-	#without background script, we could be waiting forever
-	
-	/opt/rh/nodejs010/root/usr/lib/node_modules/forever/bin/forever stop rocketchat 2>&1 >/dev/null &
-	
+  #run in background, since recent changes in forever, now blocks stop call with SIGTERM is finished
+  #but we want to wait till some time and forcibly kill after elapsed time
+  #without background script, we could be waiting forever
+  
+  /opt/rh/nodejs010/root/usr/lib/node_modules/forever/bin/forever stop rocketchat 2>&1 >/dev/null &
+  
 
-	CURRENTWAITTIME=$KILLWAITTIME
-	# wait for some time before forcefully killing the process
-	while [ $CURRENTWAITTIME -gt 0 ]; do
-		#check if the process is still running
-		checkpidexists $PID
-		if [ $? -ne 0 ]; then
-			# if not running we can break, since no more wait is needed, service is stopped
-			echo "Successful"
-			break
-		fi
-		
-	 	usleep 500000
-	 	let CURRENTWAITTIME-=500
-	 	
-	done
-	checkpidexists $PID
-	if [  $? -eq 0  ]; then
-		killtree $PID 9
-		echo 'Forced shutdown'
-	fi
+  CURRENTWAITTIME=$KILLWAITTIME
+  # wait for some time before forcefully killing the process
+  while [ $CURRENTWAITTIME -gt 0 ]; do
+    #check if the process is still running
+    checkpidexists $PID
+    if [ $? -ne 0 ]; then
+      # if not running we can break, since no more wait is needed, service is stopped
+      echo "Successful"
+      break
+    fi
+    
+     usleep 500000
+     let CURRENTWAITTIME-=500
+     
+  done
+  checkpidexists $PID
+  if [  $? -eq 0  ]; then
+    killtree $PID 9
+    echo 'Forced shutdown'
+  fi
 
-	rm -f $PIDFILE 2>&1 >/dev/null
-	rm -f $LOCKFILE 2>&1 >/dev/null
-	return 0
+  rm -f $PIDFILE 2>&1 >/dev/null
+  rm -f $LOCKFILE 2>&1 >/dev/null
+  return 0
 
 }
 
 status() {
-	#this is to ensure forever is able to find out the correct root every time
-	export FOREVER_ROOT=/root/.forever
+  #this is to ensure forever is able to find out the correct root every time
+  export FOREVER_ROOT=/root/.forever
 
     
-	STATUS=$(/opt/rh/nodejs010/root/usr/lib/node_modules/forever/bin/forever --plain list | sed 's/data:\(\s*\[[0-9]*\]\s*\(rocketchat\)\s.*\)/\2-status:\1/;tx;d;:x')
-	
-	if [ -z "$STATUS" ]; then
-		echo "rocketchat is not running"
-		RETVAL=3
-	else		
-		echo $STATUS
-		RETVAL=0
-	fi
-	return $RETVAL
+  STATUS=$(/opt/rh/nodejs010/root/usr/lib/node_modules/forever/bin/forever --plain list | sed 's/data:\(\s*\[[0-9]*\]\s*\(rocketchat\)\s.*\)/\2-status:\1/;tx;d;:x')
+  
+  if [ -z "$STATUS" ]; then
+    echo "rocketchat is not running"
+    RETVAL=3
+  else		
+    echo $STATUS
+    RETVAL=0
+  fi
+  return $RETVAL
 }
 
 case "$1" in
     start)
-	start
-	;;
+  start
+  ;;
     stop)
-	stop
-	;;
+  stop
+  ;;
     status)
-	status
-	;;
+  status
+  ;;
     restart)
-    	stop
-	start
-	;;
+      stop
+  start
+  ;;
     *)
-	echo "Usage: <servicename> {start|stop|status|restart}"
-	exit 1
-	;;
+  echo "Usage: <servicename> {start|stop|status|restart}"
+  exit 1
+  ;;
 esac
 exit $?
 
 EOF
 
-}
+    }
 }
